language: rust
rust:
- nightly
cache:
  directories:
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/target
env:
- AOC_LIB="day_1"
- AOC_LIB="day_2"
#- AOC_LIB="day_3"
script:
- "cargo test --package aoc_2018_$AOC_LIB"
