[package]
name = "aoc_2018"
version = "2.0.0"
authors = ["Joakim Hulthe <joakim@hulthe.net>"]
description = "Solver for Advent of Code 2018"
edition = "2018"

[dependencies]
clap = "2.32.0"
aoc_base = { path="aoc_base" }
aoc_2018_day_1 = { path="day_1" }
aoc_2018_day_2 = { path="day_2" }
aoc_2018_day_3 = { path="day_3" }
aoc_2018_day_4 = { path="day_4" }
