[package]
name = "aoc_2018_day_3"
version = "0.1.0"
authors = ["Joakim Hulthe <joakim@hulthe.net>"]
edition = "2018"

[dependencies]
pest = "2.0.2"
pest_derive = "2.0.1"
from-pest = "0.3.1"
pest-ast = "0.3.3"
